# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:7038

@Email=admin@localhost
@Password=Administrator1!
@BearerToken=<YourToken>

# POST /auth/login
POST {{Web_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST /auth/logout
POST {{Web_HostAddress}}/auth/logout
Authorization: Bearer {{BearerToken}}

###

# GET /users/me
GET {{Web_HostAddress}}/users/me
Authorization: Bearer {{BearerToken}}

###

# PUT /users/me
PUT {{Web_HostAddress}}/users/me
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "displayName": "System Admin"
}

###

# PUT /users/me/password
PUT {{Web_HostAddress}}/users/me/password
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "currentPassword": "{{Password}}",
  "newPassword": "Administrator2!"
}

###
